In [3]:
# Install/import required libraries
suppressWarnings({
  library(tidyverse)
  library(dplyr)
  library(ggplot2)
})

In [4]:
df <- read_csv("pre_survey_clean.csv")
head(df)

Rows: 231 Columns: 12
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (9): Survey, First Generation Status, Gender, Transfer Student, Upper v ...
dbl (3): DID #, J_total, T_total

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

  DID # Survey First Generation Status Gender Transfer Student Upper v Lower
1 1     Pre    Yes                     Man    Sophomore        L
2 2     Pre    Yes                     Man    Senior           L
3 3     Pre    No                      Woman  Junior           U
4 4     Pre    No                      Woman  Senior           U
5 5     Pre    Yes                     Man    Senior           L
6 6     Pre    No                      Woman  Senior           U
  Race/Ethnicity  Class Level J_total T_total Major               STEM
1 Asian           Sophomore   87      47      Nursing             Non-STEM
2 Hispanic/Latino Senior      71      42      Public Health       Non-STEM
3 Asian           Junior      80      50      Biological Sciences STEM
4 Hispanic/Latino Senior      86      49      Biological Sciences STEM
5 Hispanic/Latino Senior      86      55      Biological Sciences STEM
6 Asian           Senior      82      43      Biological Sciences STEM

In [5]:
df$Survey <- as.factor(df$Survey)
df$Gender <- as.factor(df$Gender)
df$`Transfer Student` <- as.factor(df$`Transfer Student`)
df$`Upper v Lower` <- as.factor(df$`Upper v Lower`)
df$`Race/Ethnicity` <- as.factor(df$`Race/Ethnicity`)
df$`Class Level` <- as.factor(df$`Class Level`)
df$STEM <- as.factor(df$STEM)

In [6]:
df

    DID # Survey First Generation Status Gender Transfer Student Upper v Lower
1    1    Pre    Yes                     Man    Sophomore        L
2    2    Pre    Yes                     Man    Senior           L
3    3    Pre    No                      Woman  Junior           U
4    4    Pre    No                      Woman  Senior           U
5    5    Pre    Yes                     Man    Senior           L
6    6    Pre    No                      Woman  Senior           U
7    7    Pre    Yes                     Woman  Sophomore        L
8    8    Pre    No                      Woman  Freshmen         L
9    9    Pre    No                      Woman  Sophomore        L
10  10    Pre    Yes                     Woman  Junior           L
11  11    Pre    No                      Woman  Senior           U
12  12    Pre    No                      Woman  Senior           U
13  13    Pre    No                      Woman  Senior           U
14  14    Pre    No                      Woman  Junior           U
15  15    Pre    No                      Woman  Senior           L
16  16    Pre    No                      Woman  Junior           L
17  17    Pre    No                      Man    Senior           U
18  18    Pre    No                      Woman  Sophomore        L
19  19    Pre    Yes                     Woman  Senior           U
20  20    Pre    Yes                     Woman  Senior           U
21  21    Pre    No                      Woman  Junior           L
22  22    Pre    Yes                     Woman  Senior           L
23  23    Pre    No                      Woman  Senior           L
24  24    Pre    No                      Woman  Senior           L
25  25    Pre    No                      Woman  Junior           L
26  26    Pre    No                      Woman  Junior           L
27  27    Pre    Yes                     Woman  Junior           L
28  28    Pre    Yes                     Woman  Sophomore        L
29  29    Pre    No                      Woman  Sophomore        L
30  30    Pre    No                      Woman  Senior           U
⋮   ⋮     ⋮      ⋮                       ⋮      ⋮                ⋮
202 202   Pre    No                      Woman  Senior           U
203 203   Pre    No                      Woman  Senior           U
204 204   Pre    No                      Woman  Senior           U
205 205   Pre    No                      Woman  Senior           U
206 206   Pre    No                      Woman  Senior           U
207 207   Pre    Yes                     Man    Senior           U
208 208   Pre    No                      Man    Senior           U
209 209   Pre    No                      Woman  Senior           U
210 210   Pre    No                      Woman  Senior           U
211 211   Pre    No                      Woman  Senior           U
212 212   Pre    No                      Woman  Senior           U
213 213   Pre    No                      Woman  Senior           U
214 214   Pre    No                      Woman  Junior           U
215 215   Pre    No                      Woman  Senior           U
216 216   Pre    No                      Woman  Sophomore        L
217 217   Pre    No                      Woman  Junior           U
218 218   Pre    No                      Man    Junior           U
219 219   Pre    Yes                     Woman  Senior           U
220 220   Pre    No                      Woman  Senior           U
221 221   Pre    No                      Woman  Senior           U
222 222   Pre    No                      Woman  Senior           U
223 223   Pre    Yes                     Woman  Senior           U
224 224   Pre    No                      Woman  Senior           U
225 225   Pre    No                      Woman  Senior           U
226 226   Pre    No                      Woman  Junior           U
227 227   Pre    No                      Woman  Junior           L
228 228   Pre    No                      Woman  Senior           U
229 229   Pre    No                      Woman  Sophomore        L
230 230   Pre    Yes                     Woman  Senior           U
231 231   Pre    Yes                     Woman  Junior           U
    Race/Ethnicity   Class Level J_total T_total Major               STEM
1   Asian            Sophomore   87      47      Nursing             Non-STEM
2   Hispanic/Latino  Senior      71      42      Public Health       Non-STEM
3   Asian            Junior      80      50      Biological Sciences STEM
4   Hispanic/Latino  Senior      86      49      Biological Sciences STEM
5   Hispanic/Latino  Senior      86      55      Biological Sciences STEM
6   Asian            Senior      82      43      Biological Sciences STEM
7   Hispanic/Latino  Sophomore   87      48      Nursing             Non-STEM
8   Asian            Freshmen    72      52      Nursing             Non-STEM
9   Asian            Sophomore   71      40      Nursing             Non-STEM
10  Hispanic/Latino  Junior      59      39      Health Sciences     Non-STEM
11  Hispanic/Latino  Senior      80      50      Biological Sciences STEM
12  Pacific Islander Senior      67      42      Biological Sciences STEM
13  Hispanic/Latino  Senior      68      45      Biological Sciences STEM
14  Asian            Junior      86      55      Nutrition           Non-STEM
15  Two or More      Senior      83      48      Biological Sciences STEM
16  Hispanic/Latino  Junior      81      50      Nursing             Non-STEM
17  Asian            Senior      59      32      Biological Sciences STEM
18  African American Sophomore   80      55      Nursing             Non-STEM
19  Hispanic/Latino  Senior      78      55      Biological Sciences STEM
20  Hispanic/Latino  Senior      75      44      Kinesiology         Non-STEM
21  Asian            Junior      71      57      Biological Sciences STEM
22  African American Senior      91      55      Health Sciences     Non-STEM
23  White            Senior      73      50      Undeclared          Non-STEM
24  White            Senior      75      47      Nursing             Non-STEM
25  Asian            Junior      84      43      Biological Sciences STEM
26  Hispanic/Latino  Junior      72      53      Biological Sciences STEM
27  Hispanic/Latino  Junior      81      49      Undeclared          Non-STEM
28  Hispanic/Latino  Sophomore   72      48      Nursing             Non-STEM
29  Hispanic/Latino  Sophomore   82      49      Nursing             Non-STEM
30  Asian            Senior      68      41      Health Sciences     Non-STEM
⋮   ⋮                ⋮           ⋮       ⋮       ⋮                   ⋮
202 Asian            Senior      88      43      Biological Sciences STEM
203 Asian            Senior      57      32      Biological Sciences STEM
204 Asian            Senior      64      46      Biological Sciences STEM
205 Hispanic/Latino  Senior      64      41      Biological Sciences STEM
206 Hispanic/Latino  Senior      82      54      Health Sciences     Non-STEM
207 White            Senior      79      54      Biological Sciences STEM
208 White            Senior      62      42      Biological Sciences STEM
209 African American Senior      81      54      Biological Sciences STEM
210 Hispanic/Latino  Senior      80      51      Biological Sciences STEM
211 White            Senior      93      56      Biological Sciences STEM
212 White            Senior      85      53      Biological Sciences STEM
213 African American Senior      71      49      Biological Sciences STEM
214 Asian            Junior      88      55      Biological Sciences STEM
215 Hispanic/Latino  Senior      91      51      Biological Sciences STEM
216 African American Sophomore   75      44      Undeclared          Non-STEM
217 Two or More      Junior      80      57      Biological Sciences STEM
218 Hispanic/Latino  Junior      91      44      Biological Sciences STEM
219 Hispanic/Latino  Senior      81      46      Biological Sciences STEM
220 Two or More      Senior      73      53      Biological Sciences STEM
221 Asian            Senior      77      51      Biological Sciences STEM
222 Hispanic/Latino  Senior      92      55      Biological Sciences STEM
223 NA               Senior      79      51      Biological Sciences STEM
224 White            Senior      80      49      Biological Sciences STEM
225 Asian            Senior      68      48      Biological Sciences STEM
226 Two or More      Junior      84      42      Kinesiology         Non-STEM
227 Two or More      Junior      71      51      Health Sciences     Non-STEM
228 Asian            Senior      64      38      Biological Sciences STEM
229 White            Sophomore   68      50      Health Sciences     Non-STEM
230 Hispanic/Latino  Senior      67      32      Biological Sciences STEM
231 Hispanic/Latino  Junior      70      50      Biological Sciences STEM